"""empty message

Revision ID: 5284e95d8e74
Revises: 93fdd4736f77
Create Date: 2023-07-03 11:52:31.758014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5284e95d8e74'
down_revision = '93fdd4736f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course', sa.String(length=100), nullable=True))
        batch_op.drop_column('class_')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('course')

    # ### end Alembic commands ###
