"""empty message

Revision ID: a52d41703066
Revises: 5284e95d8e74
Create Date: 2023-07-03 12:06:13.427061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a52d41703066'
down_revision = '5284e95d8e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_', sa.String(length=100), nullable=True))
        batch_op.drop_column('course')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('class_')

    # ### end Alembic commands ###
